[build]
  command = "unzip -o acervo-online.zip -d ."
  publish = "public"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/data"
  to = "/.netlify/functions/data"
  status = 200
